### PR TITLE
Implement connection history with "Favourites"

### PR DESCRIPTION
**Pull request by bennigraf**
Hi there!

Following the discussion in #15 I'd like to propose this implementation of a connection history list. It works as follows:

 * On any successful connection, the connection details (host, port, "roots in tabs", the `serverApplicationId` and the DateTime of the attempt) are being saved to a list in `localStorage`.
 * Those entries are being shown to the user in the connection dialog in a list below the original form fields. They are sorted most recent to oldest. Every item has a `Connection` button that allows the user to quickly connect to a server using those connection details.
 * When a user connects to a server using connection details that were in the list already, the system won't append a new entry; instead, the already existing entry will be updated with the new connection time (thus sorting it to the top of the list).
 * A user can "favourite" certain connections using the "Star" button in each list item. This will attach the entry to the top of the list. When there are multiple favourites, they are being sorted most recent to oldest as well. Additionally, the user can optionally provide a name or title to that connection. Items can be "un-favourited" by clicking the star icon again.
 * Items can be deleted by clicking the trash can icon in every list entry. (Unless one deletes items manually, the list will grow indefinitely.)

history

Regarding the code:
 * I tried to roughly follow the code style of the repository. This is my first time using TypeScript instead of plain Javascript, but I think it worked out well. 
 * The change in `ConnectionDialog` looks big because I had to switch from `Alert` to `Dialog` and do some reformatting to be able to render the list below the dialog CTAs. Besides that, the general application structure is still the same, though.
 * The storage logic is in `ConnectionHistoryProvider` to keep it away from React code/the presentation layer.

Let me know if you want to see something changed before (potentially) merging this!

Happy holidays!
Best,
Benjamin.

### CODE REVIEW

**Comment by joreg** [comment]
looking great. only one thing: when the history is full and starts scrolling i think it would be better if it doesn't scroll away the part above it. so can the history have its open scroller?Sent from Android deviceOn Dec 26, 2022 21:43, Benjamin Graf ***@***.***> wrote:Hi there!
Following the discussion in #15 I'd like to propose this implementation of a connection history list. It works as follows:
On any successful connection, the connection details (host, port, "roots in tabs", the serverApplicationId and the DateTime of the attempt) are being saved to a list in localStorage.Those entries are being shown to the user in the connection dialog in a list below the original form fields. They are sorted most recent to oldest. Every item has a Connection button that allows the user to quickly connect to a server using those connection details.When a user connects to a server using connection details that were in the list already, the system won't append a new entry; instead, the already existing entry will be updated with the new connection time (thus sorting it to the top of the list).A user can "favourite" certain connections using the "Star" button in each list item. This will attach the entry to the top of the list. When there are multiple favourites, they are being sorted most recent to oldest as well. Additionally, the user can optionally provide a name or title to that connection. Items can be "un-favourited" by clicking the star icon again.Items can be deleted by clicking the trash can icon in every list entry. (Unless one deletes items manually, the list will grow indefinitely.)

Regarding the code:
I tried to roughly follow the code style of the repository. This is my first time using TypeScript instead of plain Javascript, but I think it worked out well.The change in ConnectionDialog looks big because I had to switch from Alert to Dialog and do some reformatting to be able to render the list below the dialog CTAs. Besides that, the general application structure is still the same, though.The storage logic is in ConnectionHistoryProvider to keep it away from React code/the presentation layer.
Let me know if you want to see something changed before (potentially) merging this!
Happy holidays!
Best,
Benjamin.



You can view, comment on, or merge this pull request online at:
  https://github.com/rabbitControl/rcp-ts-client/pull/16

Commit Summary
ecf38d9  Draft of connection bookmarks functionality9281361  Ignore possibility of duplicate bookmarks1da2874  Provide some feedback on successful bookmarking22e381e  Some small refinements1628b33  Remove share connection button (from this branch)8833eca  fix indentation0118619  Initial draft of connection history list97b9f8a  Improve styling and behaviour of history listd7759c5  Remove traces of bookmarking function913607c  Improve code style, UX6e4ba06  Code style fixes

File Changes  (5 files)

    M
    src/App.css
    (51)
  
    M
    src/ConnectionDialog.tsx
    (125)
  
    A
    src/ConnectionHistoryList.tsx
    (136)
  
    A
    src/ConnectionHistoryProvider.tsx
    (127)
  
    A
    src/SetNameOfFavouriteDialog.tsx
    (82)
  

Patch Links:
https://github.com/rabbitControl/rcp-ts-client/pull/16.patchhttps://github.com/rabbitControl/rcp-ts-client/pull/16.diff

**Comment by i-n-g-o** [comment]
Hi.
Cool thanks.
Wow - looks very good so far!

Just a couple of suggestions:

- I also think only the history should scroll at the bottom of the Dialog, so the input fields always stay visible.
- Could you add a margin to the history-list so the scroll-bar would not overlay the Connect buttons in the list?
- Do you think the Disconnect button is necessary? (reload to reconnect?)
- The caret marking an entry looks like one can unfold it - is it needed?
- I think "pinning" would be more fitting than "starring" - "Pin it to the top". In that regard I suggest to use a "Pin" icon.
- Naming dialog buttons could be "Cancel" and "Pin"/"Save"?

**Comment by bennigraf** [comment]
Hi!

Thanks for your quick feedback :-). I just pushed some changes.

 * Pinning is nicer than "Favourite" indeed :-) I changed that
 * I was also able to change the scrolling to only scroll the actual list
 * I removed the disconnect thing – it was helpful for development, but most users won't ever use it, I agree
 * I also removed the caret; it was just decoration, but indeed might lead to confusion
 * I didn't add a margin; I think it looks weird if it doesn't line up with the upper part of the dialog (and the scrollbar only appears on scroll and then disappears again), so I don't think this would be an improvement but is something we have to just live with
 * About the naming – the functionality is actually either "Pin with setting a name" or "Pin without setting a name", as the pinning already happened at this point ("Cancel" doesn't prevent the pinning from happening). So for now I changed it to "Pin without name" and "Save". However, what was your impression – would you rather expect "Cancel" to abort the whole pinning process? Then I might change that and then "Cancel"/"Save" makes more sense again

Best,
Benjamin.

**Comment by i-n-g-o** [comment]
Thanks for the updates.

> About the naming – the functionality is actually either "Pin with setting a name" or "Pin without setting a name", as the pinning already happened at this point ("Cancel" doesn't prevent the pinning from happening). So for now I changed it to "Pin without name" and "Save". However, what was your experience – would you rather expect "Cancel" to abort the whole pinning process? Then I might change that and then "Cancel"/"Save" makes more sense again

I see, I thought it is pinned only when clicking "Save". How you describe it makes a lot of sense and "Cancel" is indeed not appropriate.

Then i think this is good to be merged.

**Pull request merged**
