### PR TITLE
Share connection dialog

### PR DESCRIPTION
**Pull request by bennigraf**
Hey there, and happy new year!

After the successful recent addition, I had one more thing on my mind that could be helpful: Being able to quickly share connection settings with other people. A "quick connect" feature was already implemented; one can use a special link carrying connection details to which the web client would automatically connect on load. However this was kind of hidden in code. This PR would propose a "Share" dialog that would provide this special URL for copy/paste, so that then people could share that URL with their colleagues. 

share-connection

There's a small caveat on iOS browsers though: When the web app doesn't run in a secure context (no HTTPS) (which in my understanding `rcp-ts-client` has to to be able to connect to non-secure websockets), iOS browsers don't allow access to the clipboard at all. On those devices, the content of the (read-only) input will be `select()`ed instead, so the user can tap "Copy" themself.

I hope you like this additional feature! Let me know :-)

Best,
Benjamin.

### CODE REVIEW

**Comment by joreg** [comment]
i'd be happy with this if it was implemented less "prominent". instead of having the button introduce a whole empty line at the top, how about having a rather tiny button at the end of the "connection info" line at the bottom of the widgets, where it says "connected to...".

**Comment by i-n-g-o** [comment]
Nice feature.
Could you additionally generate a QR-Code? Then another device could scan it and connect without copy paste.

Maybe there could also be sharing-button in the Connection-history?

Yes, maybe the connection button could be where the connection info is. One needs to scroll down to reach it, but that is fine I think.

**Comment by i-n-g-o** [comment]
> * About the QR code: I like the idea and I’m sure this is possible by integrating some library (I wouldn’t want to write that myself). Do you have a policy about adding npm packages?

I don't have a strong policy for dependencies. Usually i try to use something not too old, but more important is that it works and is good to integrate.

**Comment by bennigraf** [comment]
Hey!

 - I updated it as such that there is a QR code in the dialog now. It's quite prominent by nature :-), but I didn't find a good solution to i.e. expand it on tap or only show it after tapping a button; both felt somewhat weird to me.
 - I also moved the "Share" button to the footer when in an active connection. I didn't really find a way to make it less prominent than what it is now with BlueprintJS.
 - ...and added one to the connection history list. The latter gets a bit convoluted now, but I guess my device (an iPhone SE) has one of the smallest screen sizes around these days, so it should be better on most other devices ;-).

https://user-images.githubusercontent.com/108006/211217976-149a8f1b-dc89-460c-86b1-993104cb1132.mov

**Comment by i-n-g-o** [comment]
Hi.

This looks very good!
To maximize space two things could be done:
- share overlay: remove the icon
- history-list: move remove, pin and share buttons into a contextual menu.

But I'm really not sure if that is necessary.
Will merge asap.

**Comment by i-n-g-o** [comment]
Thanks

**Pull request merged**
